version: 0.2

phases:
  install:
    commands:
      # Install Apache to ensure the user exists
      - yum install -y httpd
  build:
    commands:
      # Copy the site content into Drupal's EFS file system
      - rsync -avzh --delete --exclude 'buildspec.yml' . /mnt/data/efs/files/healthequity/
      # Enforce ownership and permissions
      - chmod -R u=rX,g=rX,o= /mnt/data/efs/files/healthequity/
      - chown -R apache:apache /mnt/data/efs/files/healthequity/
