### Type definitions saved at 2022-07-18T19:11:24.790Z ###

type File implements Node @dontInfer {
  sourceInstanceName: String!
  absolutePath: String!
  relativePath: String!
  extension: String!
  size: Int!
  prettySize: String!
  modifiedTime: Date! @dateformat
  accessTime: Date! @dateformat
  changeTime: Date! @dateformat
  birthTime: Date! @dateformat
  root: String!
  dir: String!
  base: String!
  ext: String!
  name: String!
  relativeDirectory: String!
  dev: Int!
  mode: Int!
  nlink: Int!
  uid: Int!
  gid: Int!
  rdev: Int!
  ino: Float!
  atimeMs: Float!
  mtimeMs: Float!
  ctimeMs: Float!
  atime: Date! @dateformat
  mtime: Date! @dateformat
  ctime: Date! @dateformat
  birthtime: Date @deprecated(reason: "Use `birthTime` instead")
  birthtimeMs: Float @deprecated(reason: "Use `birthTime` instead")
  blksize: Int
  blocks: Int
  url: String
}

type Directory implements Node @dontInfer {
  sourceInstanceName: String!
  absolutePath: String!
  relativePath: String!
  extension: String!
  size: Int!
  prettySize: String!
  modifiedTime: Date! @dateformat
  accessTime: Date! @dateformat
  changeTime: Date! @dateformat
  birthTime: Date! @dateformat
  root: String!
  dir: String!
  base: String!
  ext: String!
  name: String!
  relativeDirectory: String!
  dev: Int!
  mode: Int!
  nlink: Int!
  uid: Int!
  gid: Int!
  rdev: Int!
  ino: Float!
  atimeMs: Float!
  mtimeMs: Float!
  ctimeMs: Float!
  atime: Date! @dateformat
  mtime: Date! @dateformat
  ctime: Date! @dateformat
  birthtime: Date @deprecated(reason: "Use `birthTime` instead")
  birthtimeMs: Float @deprecated(reason: "Use `birthTime` instead")
  blksize: Int
  blocks: Int
}

type Site implements Node @dontInfer {
  buildTime: Date @dateformat
  siteMetadata: SiteSiteMetadata
  pathPrefix: String
  polyfill: Boolean
}

type SiteSiteMetadata {
  title: String
  description: String
  author: String
  image: String
}

type SiteFunction implements Node @dontInfer {
  functionRoute: String!
  pluginName: String!
  originalAbsoluteFilePath: String!
  originalRelativeFilePath: String!
  relativeCompiledFilePath: String!
  absoluteCompiledFilePath: String!
  matchPath: String
}

type SitePage implements Node @dontInfer {
  path: String!
  component: String!
  internalComponentName: String!
  componentChunkName: String!
  matchPath: String
}

type SitePlugin implements Node @dontInfer {
  resolve: String
  name: String
  version: String
  nodeAPIs: [String]
  browserAPIs: [String]
  ssrAPIs: [String]
  pluginFilepath: String
  pluginOptions: SitePluginPluginOptions
  packageJson: SitePluginPackageJson
}

type SitePluginPluginOptions {
  displayName: Boolean
  fileName: Boolean
  minify: Boolean
  namespace: String
  transpileTemplateLiterals: Boolean
  pure: Boolean
  disableVendorPrefixes: Boolean
  pathToConfigModule: String
  component: String
  name: String
  path: String
  base64Width: Int
  stripMetadata: Boolean
  defaultQuality: Int
  failOnError: Boolean
  short_name: String
  start_url: String
  background_color: String
  theme_color: String
  display: String
  icon: String
  legacy: Boolean
  theme_color_in_head: Boolean
  cache_busting_mode: String
  crossOrigin: String
  include_favicon: Boolean
  cacheDigest: String
  offset: Int
  update: String
  id: String
  includeInDevelopment: Boolean
  defaultDataLayer: SitePluginPluginOptionsDefaultDataLayer
  routeChangeEventName: String
  enableWebVitalsTracking: Boolean
  selfHostedOrigin: String
  baseUrl: String
  concurrentFileRequests: Int
  skipFileDownloads: Boolean
  disallowedLinkTypes: [String]
  filters: SitePluginPluginOptionsFilters
  concurrentAPIRequests: Int
  pathCheck: Boolean
  allExtensions: Boolean
  isTSX: Boolean
  jsxPragma: String
}

type SitePluginPluginOptionsDefaultDataLayer {
  type: String
  value: SitePluginPluginOptionsDefaultDataLayerValue
}

type SitePluginPluginOptionsDefaultDataLayerValue {
  platform: String
  algoliaIndexName: String
}

type SitePluginPluginOptionsFilters {
  node__health_equity_disparities: String @proxy(from: "node--health_equity_disparities", fromNode: false)
  node__health_equity_press_kit: String @proxy(from: "node--health_equity_press_kit", fromNode: false)
  node__health_equity_blog: String @proxy(from: "node--health_equity_blog", fromNode: false)
  node__health_equity_promotion: String @proxy(from: "node--health_equity_promotion", fromNode: false)
  node__health_equity_plan_profile: String @proxy(from: "node--health_equity_plan_profile", fromNode: false)
  node__health_equity_advisory_panel: String @proxy(from: "node--health_equity_advisory_panel", fromNode: false)
}

type SitePluginPackageJson {
  name: String
  description: String
  version: String
  main: String
  license: String
  dependencies: [SitePluginPackageJsonDependencies]
  devDependencies: [SitePluginPackageJsonDevDependencies]
  peerDependencies: [SitePluginPackageJsonPeerDependencies]
  keywords: [String]
}

type SitePluginPackageJsonDependencies {
  name: String
  version: String
}

type SitePluginPackageJsonDevDependencies {
  name: String
  version: String
}

type SitePluginPackageJsonPeerDependencies {
  name: String
  version: String
}

type SiteBuildMetadata implements Node @dontInfer {
  buildTime: Date @dateformat
}

enum GatsbyImageFormat {
  NO_CHANGE
  AUTO
  JPG
  PNG
  WEBP
  AVIF
}

enum GatsbyImageLayout {
  FIXED
  FULL_WIDTH
  CONSTRAINED
}

enum GatsbyImagePlaceholder {
  DOMINANT_COLOR
  TRACED_SVG
  BLURRED
  NONE
}

enum ImageFormat {
  NO_CHANGE
  AUTO
  JPG
  PNG
  WEBP
  AVIF
}

enum ImageFit {
  COVER
  CONTAIN
  FILL
  INSIDE
  OUTSIDE
}

enum ImageLayout {
  FIXED
  FULL_WIDTH
  CONSTRAINED
}

enum ImageCropFocus {
  CENTER
  NORTH
  NORTHEAST
  EAST
  SOUTHEAST
  SOUTH
  SOUTHWEST
  WEST
  NORTHWEST
  ENTROPY
  ATTENTION
}

input DuotoneGradient {
  highlight: String!
  shadow: String!
  opacity: Int
}

enum PotraceTurnPolicy {
  TURNPOLICY_BLACK
  TURNPOLICY_WHITE
  TURNPOLICY_LEFT
  TURNPOLICY_RIGHT
  TURNPOLICY_MINORITY
  TURNPOLICY_MAJORITY
}

input Potrace {
  turnPolicy: PotraceTurnPolicy
  turdSize: Float
  alphaMax: Float
  optCurve: Boolean
  optTolerance: Float
  threshold: Int
  blackOnWhite: Boolean
  color: String
  background: String
}

type ImageSharpFixed {
  base64: String
  tracedSVG: String
  aspectRatio: Float
  width: Float!
  height: Float!
  src: String!
  srcSet: String!
  srcWebp: String
  srcSetWebp: String
  originalName: String
}

type ImageSharpFluid {
  base64: String
  tracedSVG: String
  aspectRatio: Float!
  src: String!
  srcSet: String!
  srcWebp: String
  srcSetWebp: String
  sizes: String!
  originalImg: String
  originalName: String
  presentationWidth: Int!
  presentationHeight: Int!
}

enum ImagePlaceholder {
  DOMINANT_COLOR
  TRACED_SVG
  BLURRED
  NONE
}

input BlurredOptions {
  """Width of the generated low-res preview. Default is 20px"""
  width: Int

  """
  Force the output format for the low-res preview. Default is to use the same
  format as the input. You should rarely need to change this
  """
  toFormat: ImageFormat
}

input JPGOptions {
  quality: Int
  progressive: Boolean = true
}

input PNGOptions {
  quality: Int
  compressionSpeed: Int = 4
}

input WebPOptions {
  quality: Int
}

input AVIFOptions {
  quality: Int
  lossless: Boolean
  speed: Int
}

input TransformOptions {
  grayscale: Boolean = false
  duotone: DuotoneGradient
  rotate: Int = 0
  trim: Float = 0
  cropFocus: ImageCropFocus = ATTENTION
  fit: ImageFit = COVER
}

type ImageSharpOriginal {
  width: Float
  height: Float
  src: String
}

type ImageSharpResize {
  src: String
  tracedSVG: String
  width: Int
  height: Int
  aspectRatio: Float
  originalName: String
}

type ImageSharp implements Node @childOf(mimeTypes: [], types: ["File"]) @dontInfer {
  fixed(width: Int, height: Int, base64Width: Int, jpegProgressive: Boolean = true, pngCompressionSpeed: Int = 4, grayscale: Boolean = false, duotone: DuotoneGradient, traceSVG: Potrace, quality: Int, jpegQuality: Int, pngQuality: Int, webpQuality: Int, toFormat: ImageFormat = AUTO, toFormatBase64: ImageFormat = AUTO, cropFocus: ImageCropFocus = ATTENTION, fit: ImageFit = COVER, background: String = "rgba(0,0,0,1)", rotate: Int = 0, trim: Float = 0): ImageSharpFixed
  fluid(
    maxWidth: Int
    maxHeight: Int
    base64Width: Int
    grayscale: Boolean = false
    jpegProgressive: Boolean = true
    pngCompressionSpeed: Int = 4
    duotone: DuotoneGradient
    traceSVG: Potrace
    quality: Int
    jpegQuality: Int
    pngQuality: Int
    webpQuality: Int
    toFormat: ImageFormat = AUTO
    toFormatBase64: ImageFormat = AUTO
    cropFocus: ImageCropFocus = ATTENTION
    fit: ImageFit = COVER
    background: String = "rgba(0,0,0,1)"
    rotate: Int = 0
    trim: Float = 0
    sizes: String = ""

    """
    A list of image widths to be generated. Example: [ 200, 340, 520, 890 ]
    """
    srcSetBreakpoints: [Int] = []
  ): ImageSharpFluid
  gatsbyImageData(
    """
    The layout for the image.
    FIXED: A static image sized, that does not resize according to the screen width
    FULL_WIDTH: The image resizes to fit its container. Pass a "sizes" option if
    it isn't going to be the full width of the screen.
    CONSTRAINED: Resizes to fit its container, up to a maximum width, at which point it will remain fixed in size.
    """
    layout: ImageLayout = CONSTRAINED

    """
    The display width of the generated image for layout = FIXED, and the maximum
    display width of the largest image for layout = CONSTRAINED.
    Ignored if layout = FLUID.
    """
    width: Int

    """
    The display height of the generated image for layout = FIXED, and the
    maximum display height of the largest image for layout = CONSTRAINED.
    The image will be cropped if the aspect ratio does not match the source
    image. If omitted, it is calculated from the supplied width,
    matching the aspect ratio of the source image.
    """
    height: Int

    """
    If set along with width or height, this will set the value of the other
    dimension to match the provided aspect ratio, cropping the image if needed.
    If neither width or height is provided, height will be set based on the intrinsic width of the source image.
    """
    aspectRatio: Float

    """
    Format of generated placeholder image, displayed while the main image loads.
    BLURRED: a blurred, low resolution image, encoded as a base64 data URI (default)
    DOMINANT_COLOR: a solid color, calculated from the dominant color of the image.
    TRACED_SVG: a low-resolution traced SVG of the image.
    NONE: no placeholder. Set "background" to use a fixed background color.
    """
    placeholder: ImagePlaceholder

    """
    Options for the low-resolution placeholder image. Set placeholder to "BLURRED" to use this
    """
    blurredOptions: BlurredOptions

    """
    Options for traced placeholder SVGs. You also should set placeholder to "TRACED_SVG".
    """
    tracedSVGOptions: Potrace

    """
    The image formats to generate. Valid values are "AUTO" (meaning the same
    format as the source image), "JPG", "PNG", "WEBP" and "AVIF".
    The default value is [AUTO, WEBP], and you should rarely need to change
    this. Take care if you specify JPG or PNG when you do
    not know the formats of the source images, as this could lead to unwanted
    results such as converting JPEGs to PNGs. Specifying
    both PNG and JPG is not supported and will be ignored.
    """
    formats: [ImageFormat]

    """
    A list of image pixel densities to generate. It will never generate images
    larger than the source, and will always include a 1x image.
    Default is [ 1, 2 ] for FIXED images, meaning 1x and 2x and [0.25, 0.5, 1,
    2] for CONSTRAINED. In this case, an image with a constrained layout
    and width = 400 would generate images at 100, 200, 400 and 800px wide.
    Ignored for FULL_WIDTH images, which use breakpoints instead
    """
    outputPixelDensities: [Float]

    """
    Specifies the image widths to generate. For FIXED and CONSTRAINED images it
    is better to allow these to be determined automatically,
    based on the image size. For FULL_WIDTH images this can be used to override
    the default, which is [750, 1080, 1366, 1920].
    It will never generate any images larger than the source.
    """
    breakpoints: [Int]

    """
    The "sizes" property, passed to the img tag. This describes the display size of the image.
    This does not affect the generated images, but is used by the browser to decide which images to download.
    You should usually leave this blank, and a suitable value will be calculated. The exception is if a FULL_WIDTH image
    does not actually span the full width of the screen, in which case you should pass the correct size here.
    """
    sizes: String

    """The default quality. This is overridden by any format-specific options"""
    quality: Int

    """Options to pass to sharp when generating JPG images."""
    jpgOptions: JPGOptions

    """Options to pass to sharp when generating PNG images."""
    pngOptions: PNGOptions

    """Options to pass to sharp when generating WebP images."""
    webpOptions: WebPOptions

    """Options to pass to sharp when generating AVIF images."""
    avifOptions: AVIFOptions

    """
    Options to pass to sharp to control cropping and other image manipulations.
    """
    transformOptions: TransformOptions

    """
    Background color applied to the wrapper. Also passed to sharp to use as a
    background when "letterboxing" an image to another aspect ratio.
    """
    backgroundColor: String
  ): JSON!
  original: ImageSharpOriginal
  resize(width: Int, height: Int, quality: Int, jpegQuality: Int, pngQuality: Int, webpQuality: Int, jpegProgressive: Boolean = true, pngCompressionLevel: Int = 9, pngCompressionSpeed: Int = 4, grayscale: Boolean = false, duotone: DuotoneGradient, base64: Boolean = false, traceSVG: Potrace, toFormat: ImageFormat = AUTO, cropFocus: ImageCropFocus = ATTENTION, fit: ImageFit = COVER, background: String = "rgba(0,0,0,1)", rotate: Int = 0, trim: Float = 0): ImageSharpResize
}

union heRelatedContentUnion = node__health_equity_plan_profile | node__health_equity_blog | node__health_equity_promotion

union hoaRelatedContentUnion = node__hoa_insight | node__hoa_page | node__podcast | node__video | node__health_america_page | node__page | node__press_release | node__bcbs_covid_article

type node__health_equity_promotion implements Node @dontInfer {
  field_he_author: String
  relationships: node__health_equity_promotionRelationships
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__health_equity_promotionPath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__health_equity_promotionBody
  field_he_reading_time: String
  node_type: node__health_equity_promotionNode_type
  revision_uid: node__health_equity_promotionRevision_uid
  uid: node__health_equity_promotionUid
  field_bcbs_plan: [node__health_equity_promotionField_bcbs_plan]
  field_he_featured_image: node__health_equity_promotionField_he_featured_image
  field_states: [node__health_equity_promotionField_states]
  field_topics: [node__health_equity_promotionField_topics]
}

type node__health_equity_promotionRelationships {
  field_he_related_content: [heRelatedContentUnion] @link(by: "id", from: "field_he_related_content___NODE")
  field_he_hoa_related_content: [hoaRelatedContentUnion] @link(by: "id", from: "field_he_hoa_related_content___NODE")
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_bcbs_plan: [taxonomy_term__bcbs_plan] @link(by: "id", from: "field_bcbs_plan___NODE")
  field_he_featured_image: file__file @link(by: "id", from: "field_he_featured_image___NODE")
  field_states: [taxonomy_term__states] @link(by: "id", from: "field_states___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
}

type node_type__node_type implements Node @dontInfer {
  drupal_id: String
  langcode: String
  status: Boolean
  dependencies: node_type__node_typeDependencies
  third_party_settings: node_type__node_typeThird_party_settings
  name: String
  drupal_internal__type: String
  description: String
  help: String
  new_revision: Boolean
  preview_mode: Int
  display_submitted: Boolean
  relationships: node_type__node_typeRelationships
}

type node_type__node_typeDependencies {
  module: [String]
}

type node_type__node_typeThird_party_settings {
  menu_ui: node_type__node_typeThird_party_settingsMenu_ui
}

type node_type__node_typeThird_party_settingsMenu_ui {
  available_menus: [String]
  parent: String
}

type node_type__node_typeRelationships {
  node__bcbs_covid_article: [node__bcbs_covid_article] @link(by: "id", from: "node__bcbs_covid_article___NODE")
  node__health_america_page: [node__health_america_page] @link(by: "id", from: "node__health_america_page___NODE")
  node__health_equity_advisory_panel: [node__health_equity_advisory_panel] @link(by: "id", from: "node__health_equity_advisory_panel___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
  node__health_equity_disparities: [node__health_equity_disparities] @link(by: "id", from: "node__health_equity_disparities___NODE")
  node__health_equity_faqs: [node__health_equity_faqs] @link(by: "id", from: "node__health_equity_faqs___NODE")
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  node__health_equity_press_kit: [node__health_equity_press_kit] @link(by: "id", from: "node__health_equity_press_kit___NODE")
  node__health_equity_promotion: [node__health_equity_promotion] @link(by: "id", from: "node__health_equity_promotion___NODE")
  node__hoa_homepage: [node__hoa_homepage] @link(by: "id", from: "node__hoa_homepage___NODE")
  node__hoa_insight: [node__hoa_insight] @link(by: "id", from: "node__hoa_insight___NODE")
  node__hoa_page: [node__hoa_page] @link(by: "id", from: "node__hoa_page___NODE")
  node__hoa_topic: [node__hoa_topic] @link(by: "id", from: "node__hoa_topic___NODE")
  node__page: [node__page] @link(by: "id", from: "node__page___NODE")
  node__podcast: [node__podcast] @link(by: "id", from: "node__podcast___NODE")
  node__press_release: [node__press_release] @link(by: "id", from: "node__press_release___NODE")
  node__video: [node__video] @link(by: "id", from: "node__video___NODE")
}

type node__bcbs_covid_article implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__bcbs_covid_articlePath
  rh_action: String
  rh_redirect: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__bcbs_covid_articleBody
  field_meta_tags: node__bcbs_covid_articleField_meta_tags
  relationships: node__bcbs_covid_articleRelationships
  node_type: node__bcbs_covid_articleNode_type
  revision_uid: node__bcbs_covid_articleRevision_uid
  uid: node__bcbs_covid_articleUid
  field_bcbs_plan: [node__bcbs_covid_articleField_bcbs_plan]
  field_featured_image: node__bcbs_covid_articleField_featured_image
  field_states: [node__bcbs_covid_articleField_states]
}

type node__bcbs_covid_articlePath {
  alias: String
  pid: Int
  langcode: String
}

type node__bcbs_covid_articleBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__bcbs_covid_articleField_meta_tags {
  og_image_url: String
  twitter_cards_type: String
  twitter_cards_description: String
  twitter_cards_title: String
  twitter_cards_image: String
}

type node__bcbs_covid_articleRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_bcbs_plan: [taxonomy_term__bcbs_plan] @link(by: "id", from: "field_bcbs_plan___NODE")
  field_states: [taxonomy_term__states] @link(by: "id", from: "field_states___NODE")
}

type user__user implements Node @dontInfer {
  drupal_id: String
  display_name: String
  relationships: user__userRelationships
}

type user__userRelationships {
  block_content__basic: [block_content__basic] @link(by: "id", from: "block_content__basic___NODE")
  block_content__section_header: [block_content__section_header] @link(by: "id", from: "block_content__section_header___NODE")
  node__press_release: [node__press_release] @link(by: "id", from: "node__press_release___NODE")
  node__bcbs_covid_article: [node__bcbs_covid_article] @link(by: "id", from: "node__bcbs_covid_article___NODE")
  node__health_america_page: [node__health_america_page] @link(by: "id", from: "node__health_america_page___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  node__health_equity_promotion: [node__health_equity_promotion] @link(by: "id", from: "node__health_equity_promotion___NODE")
  node__hoa_homepage: [node__hoa_homepage] @link(by: "id", from: "node__hoa_homepage___NODE")
  node__hoa_insight: [node__hoa_insight] @link(by: "id", from: "node__hoa_insight___NODE")
  node__hoa_page: [node__hoa_page] @link(by: "id", from: "node__hoa_page___NODE")
  node__hoa_topic: [node__hoa_topic] @link(by: "id", from: "node__hoa_topic___NODE")
  node__page: [node__page] @link(by: "id", from: "node__page___NODE")
  node__video: [node__video] @link(by: "id", from: "node__video___NODE")
  node__podcast: [node__podcast] @link(by: "id", from: "node__podcast___NODE")
  file__file: [file__file] @link(by: "id", from: "file__file___NODE")
  node__health_equity_disparities: [node__health_equity_disparities] @link(by: "id", from: "node__health_equity_disparities___NODE")
  node__health_equity_press_kit: [node__health_equity_press_kit] @link(by: "id", from: "node__health_equity_press_kit___NODE")
  node__health_equity_faqs: [node__health_equity_faqs] @link(by: "id", from: "node__health_equity_faqs___NODE")
  node__health_equity_advisory_panel: [node__health_equity_advisory_panel] @link(by: "id", from: "node__health_equity_advisory_panel___NODE")
}

type block_content__basic implements Node @dontInfer {
  drupal_id: String
  drupal_internal__id: Int
  drupal_internal__revision_id: Int
  langcode: String
  revision_created: Date @dateformat
  status: Boolean
  info: String
  changed: Date @dateformat
  reusable: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  metatag_normalized: [block_content__basicMetatag_normalized]
  content_translation_source: String
  content_translation_outdated: Boolean
  content_translation_created: Date @dateformat
  body: block_content__basicBody
  relationships: block_content__basicRelationships
  block_content_type: block_content__basicBlock_content_type
  revision_user: block_content__basicRevision_user
  content_translation_uid: block_content__basicContent_translation_uid
}

type block_content__basicMetatag_normalized {
  tag: String
  attributes: block_content__basicMetatag_normalizedAttributes
}

type block_content__basicMetatag_normalizedAttributes {
  name: String
  content: String
}

type block_content__basicBody {
  value: String
  format: String
  processed: String
  summary: String
}

type block_content__basicRelationships {
  revision_user: user__user @link(by: "id", from: "revision_user___NODE")
  content_translation_uid: user__user @link(by: "id", from: "content_translation_uid___NODE")
}

type block_content__basicBlock_content_type {
  drupal_internal__target_id: String
}

type block_content__basicRevision_user {
  drupal_internal__target_id: Int
}

type block_content__basicContent_translation_uid {
  drupal_internal__target_id: Int
}

type block_content__section_header implements Node @dontInfer {
  drupal_id: String
  drupal_internal__id: Int
  drupal_internal__revision_id: Int
  langcode: String
  revision_created: Date @dateformat
  status: Boolean
  info: String
  changed: Date @dateformat
  reusable: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  content_translation_source: String
  content_translation_outdated: Boolean
  content_translation_created: Date @dateformat
  relationships: block_content__section_headerRelationships
  block_content_type: block_content__section_headerBlock_content_type
  content_translation_uid: block_content__section_headerContent_translation_uid
}

type block_content__section_headerRelationships {
  content_translation_uid: user__user @link(by: "id", from: "content_translation_uid___NODE")
}

type block_content__section_headerBlock_content_type {
  drupal_internal__target_id: String
}

type block_content__section_headerContent_translation_uid {
  drupal_internal__target_id: Int
}

type node__press_release implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__press_releasePath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__press_releaseBody
  field_field_press_release_import: Date @dateformat
  field_meta_tags: node__press_releaseField_meta_tags
  field_sub_title: String
  relationships: node__press_releaseRelationships
  node_type: node__press_releaseNode_type
  revision_uid: node__press_releaseRevision_uid
  uid: node__press_releaseUid
  field_bcbs_plan: [node__press_releaseField_bcbs_plan]
  field_file_attachments: [node__press_releaseField_file_attachments]
  field_topics: [node__press_releaseField_topics]
}

type node__press_releasePath {
  alias: String
  pid: Int
  langcode: String
}

type node__press_releaseBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__press_releaseField_meta_tags {
  description: String
}

type node__press_releaseRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_bcbs_plan: [taxonomy_term__bcbs_plan] @link(by: "id", from: "field_bcbs_plan___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
  node__health_america_page: [node__health_america_page] @link(by: "id", from: "node__health_america_page___NODE")
}

type taxonomy_term__bcbs_plan implements Node @dontInfer {
  drupal_id: String
  drupal_internal__tid: Int
  drupal_internal__revision_id: Int
  langcode: String
  status: Boolean
  name: String
  weight: Int
  changed: Date @dateformat
  default_langcode: Boolean
  revision_translation_affected: Boolean
  rh_action: String
  rh_redirect_response: Int
  field_more_news_text: taxonomy_term__bcbs_planField_more_news_text
  relationships: taxonomy_term__bcbs_planRelationships
  vid: taxonomy_term__bcbs_planVid
}

type taxonomy_term__bcbs_planField_more_news_text {
  value: String
  format: String
  processed: String
  summary: String
}

type taxonomy_term__bcbs_planRelationships {
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  node__press_release: [node__press_release] @link(by: "id", from: "node__press_release___NODE")
  parent: [taxonomy_term__bcbs_plan] @link(by: "id", from: "parent___NODE")
  node__bcbs_covid_article: [node__bcbs_covid_article] @link(by: "id", from: "node__bcbs_covid_article___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
  taxonomy_term__bcbs_plan: [taxonomy_term__bcbs_plan] @link(by: "id", from: "taxonomy_term__bcbs_plan___NODE")
  node__health_equity_promotion: [node__health_equity_promotion] @link(by: "id", from: "node__health_equity_promotion___NODE")
}

type node__health_equity_plan_profile implements Node @dontInfer {
  title: String
  relationships: node__health_equity_plan_profileRelationships
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  revision_log: String
  status: Boolean
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__health_equity_plan_profilePath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__health_equity_plan_profileBody
  field_he_author: String
  field_he_reading_time: String
  node_type: node__health_equity_plan_profileNode_type
  revision_uid: node__health_equity_plan_profileRevision_uid
  uid: node__health_equity_plan_profileUid
  field_bcbs_plan: [node__health_equity_plan_profileField_bcbs_plan]
  field_he_featured_image: node__health_equity_plan_profileField_he_featured_image
  field_he_hoa_related_content: [node__health_equity_plan_profileField_he_hoa_related_content]
  field_he_related_content: [node__health_equity_plan_profileField_he_related_content]
  field_states: [node__health_equity_plan_profileField_states]
  field_topics: [node__health_equity_plan_profileField_topics]
}

type node__health_equity_plan_profileRelationships {
  field_he_related_content: [heRelatedContentUnion] @link(by: "id", from: "field_he_related_content___NODE")
  field_he_hoa_related_content: [hoaRelatedContentUnion] @link(by: "id", from: "field_he_hoa_related_content___NODE")
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_bcbs_plan: [taxonomy_term__bcbs_plan] @link(by: "id", from: "field_bcbs_plan___NODE")
  field_he_featured_image: file__file @link(by: "id", from: "field_he_featured_image___NODE")
  field_states: [taxonomy_term__states] @link(by: "id", from: "field_states___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
}

type file__file implements Node @dontInfer {
  drupal_id: String
  drupal_internal__fid: Int
  langcode: String
  filename: String
  uri: file__fileUri
  filemime: String
  filesize: Int
  status: Boolean
  created: Date @dateformat
  changed: Date @dateformat
  relationships: file__fileRelationships
  uid: file__fileUid
  localFile: File @link(by: "id", from: "localFile___NODE")
}

type file__fileUri {
  value: String
  url: String
}

type file__fileRelationships {
  node__health_equity_advisory_panel: [node__health_equity_advisory_panel] @link(by: "id", from: "node__health_equity_advisory_panel___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
  node__health_equity_disparities: [node__health_equity_disparities] @link(by: "id", from: "node__health_equity_disparities___NODE")
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  node__health_equity_press_kit: [node__health_equity_press_kit] @link(by: "id", from: "node__health_equity_press_kit___NODE")
  node__health_equity_promotion: [node__health_equity_promotion] @link(by: "id", from: "node__health_equity_promotion___NODE")
}

type node__health_equity_advisory_panel implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__health_equity_advisory_panelPath
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__health_equity_advisory_panelBody
  field_he_company: String
  field_he_lead: String
  field_he_position: String
  relationships: node__health_equity_advisory_panelRelationships
  node_type: node__health_equity_advisory_panelNode_type
  revision_uid: node__health_equity_advisory_panelRevision_uid
  uid: node__health_equity_advisory_panelUid
  field_he_ap_featured_image: node__health_equity_advisory_panelField_he_ap_featured_image
}

type node__health_equity_advisory_panelPath {
  langcode: String
}

type node__health_equity_advisory_panelBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__health_equity_advisory_panelRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_he_ap_featured_image: file__file @link(by: "id", from: "field_he_ap_featured_image___NODE")
}

type node__health_equity_advisory_panelNode_type {
  drupal_internal__target_id: String
}

type node__health_equity_advisory_panelRevision_uid {
  drupal_internal__target_id: Int
}

type node__health_equity_advisory_panelUid {
  drupal_internal__target_id: Int
}

type node__health_equity_advisory_panelField_he_ap_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__health_equity_blog implements Node @dontInfer {
  relationships: node__health_equity_blogRelationships
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__health_equity_blogPath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__health_equity_blogBody
  field_he_author: String
  field_he_reading_time: String
  node_type: node__health_equity_blogNode_type
  revision_uid: node__health_equity_blogRevision_uid
  uid: node__health_equity_blogUid
  field_bcbs_plan: [node__health_equity_blogField_bcbs_plan]
  field_he_featured_image: node__health_equity_blogField_he_featured_image
  field_he_hoa_related_content: [node__health_equity_blogField_he_hoa_related_content]
  field_he_related_content: [node__health_equity_blogField_he_related_content]
  field_states: [node__health_equity_blogField_states]
  field_topics: [node__health_equity_blogField_topics]
}

type node__health_equity_blogRelationships {
  field_he_related_content: [heRelatedContentUnion] @link(by: "id", from: "field_he_related_content___NODE")
  field_he_hoa_related_content: [hoaRelatedContentUnion] @link(by: "id", from: "field_he_hoa_related_content___NODE")
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_bcbs_plan: [taxonomy_term__bcbs_plan] @link(by: "id", from: "field_bcbs_plan___NODE")
  field_he_featured_image: file__file @link(by: "id", from: "field_he_featured_image___NODE")
  field_states: [taxonomy_term__states] @link(by: "id", from: "field_states___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
}

type taxonomy_term__states implements Node @dontInfer {
  drupal_id: String
  drupal_internal__tid: Int
  drupal_internal__revision_id: Int
  langcode: String
  status: Boolean
  name: String
  weight: Int
  changed: Date @dateformat
  default_langcode: Boolean
  revision_translation_affected: Boolean
  rh_action: String
  rh_redirect_response: Int
  relationships: taxonomy_term__statesRelationships
  vid: taxonomy_term__statesVid
}

type taxonomy_term__statesRelationships {
  node__bcbs_covid_article: [node__bcbs_covid_article] @link(by: "id", from: "node__bcbs_covid_article___NODE")
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  node__video: [node__video] @link(by: "id", from: "node__video___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
  node__health_equity_promotion: [node__health_equity_promotion] @link(by: "id", from: "node__health_equity_promotion___NODE")
  node__podcast: [node__podcast] @link(by: "id", from: "node__podcast___NODE")
}

type node__video implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__videoPath
  rh_action: String
  rh_redirect_response: Int
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__videoBody
  field_meta_tags: node__videoField_meta_tags
  field_published: Date @dateformat
  field_video_url: String
  relationships: node__videoRelationships
  node_type: node__videoNode_type
  revision_uid: node__videoRevision_uid
  uid: node__videoUid
  field_series: node__videoField_series
  field_tags: node__videoField_tags
  field_hoa_content: node__videoField_hoa_content
  field_topics: [node__videoField_topics]
  field_states: [node__videoField_states]
  field_featured_image: node__videoField_featured_image
}

type node__videoPath {
  alias: String
  pid: Int
  langcode: String
}

type node__videoBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__videoField_meta_tags {
  title: String
  keywords: String
  description: String
}

type node__videoRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_series: taxonomy_term__topic @link(by: "id", from: "field_series___NODE")
  field_states: [taxonomy_term__states] @link(by: "id", from: "field_states___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
  field_tags: taxonomy_term__topic @link(by: "id", from: "field_tags___NODE")
  field_hoa_content: taxonomy_term__the_health_of_america @link(by: "id", from: "field_hoa_content___NODE")
}

type taxonomy_term__topic implements Node @dontInfer {
  drupal_id: String
  drupal_internal__tid: Int
  drupal_internal__revision_id: Int
  langcode: String
  revision_created: Date @dateformat
  status: Boolean
  name: String
  description: taxonomy_term__topicDescription
  weight: Int
  changed: Date @dateformat
  default_langcode: Boolean
  revision_translation_affected: Boolean
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  field_long_description: taxonomy_term__topicField_long_description
  relationships: taxonomy_term__topicRelationships
  vid: taxonomy_term__topicVid
}

type taxonomy_term__topicDescription {
  value: String
  format: String
  processed: String
}

type taxonomy_term__topicField_long_description {
  value: String
  format: String
  processed: String
}

type taxonomy_term__topicRelationships {
  node__video: [node__video] @link(by: "id", from: "node__video___NODE")
  node__health_america_page: [node__health_america_page] @link(by: "id", from: "node__health_america_page___NODE")
  node__hoa_insight: [node__hoa_insight] @link(by: "id", from: "node__hoa_insight___NODE")
  node__hoa_page: [node__hoa_page] @link(by: "id", from: "node__hoa_page___NODE")
  node__hoa_topic: [node__hoa_topic] @link(by: "id", from: "node__hoa_topic___NODE")
  node__health_equity_disparities: [node__health_equity_disparities] @link(by: "id", from: "node__health_equity_disparities___NODE")
  node__press_release: [node__press_release] @link(by: "id", from: "node__press_release___NODE")
  node__podcast: [node__podcast] @link(by: "id", from: "node__podcast___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  node__health_equity_promotion: [node__health_equity_promotion] @link(by: "id", from: "node__health_equity_promotion___NODE")
}

type node__health_america_page implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__health_america_pagePath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__health_america_pageBody
  field_exclude_from_list: Boolean
  field_meta_tags: node__health_america_pageField_meta_tags
  field_sub_title: String
  relationships: node__health_america_pageRelationships
  node_type: node__health_america_pageNode_type
  revision_uid: node__health_america_pageRevision_uid
  uid: node__health_america_pageUid
  field_featured_image: node__health_america_pageField_featured_image
  field_file_attachments: [node__health_america_pageField_file_attachments]
  field_hoa_content: node__health_america_pageField_hoa_content
  field_related_pr: node__health_america_pageField_related_pr
  field_topics: [node__health_america_pageField_topics]
  field_appendix_data: [node__health_america_pageField_appendix_data]
  field_download_infographic: [node__health_america_pageField_download_infographic]
  field_curated_featured_content: [node__health_america_pageField_curated_featured_content]
}

type node__health_america_pagePath {
  alias: String
  pid: Int
  langcode: String
}

type node__health_america_pageBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__health_america_pageField_meta_tags {
  keywords: String
  abstract: String
  description: String
  title: String
  news_keywords: String
  article_tag: String
  twitter_cards_image: String
}

type node__health_america_pageRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_curated_featured_content: [node__health_america_pagenode__podcastUnion] @link(by: "id", from: "field_curated_featured_content___NODE")
  field_hoa_content: taxonomy_term__the_health_of_america @link(by: "id", from: "field_hoa_content___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  field_related_pr: node__press_release @link(by: "id", from: "field_related_pr___NODE")
  node__hoa_insight: [node__hoa_insight] @link(by: "id", from: "node__hoa_insight___NODE")
  node__health_america_page: [node__health_america_page] @link(by: "id", from: "node__health_america_page___NODE")
  node__health_equity_blog: [node__health_equity_blog] @link(by: "id", from: "node__health_equity_blog___NODE")
}

union node__health_america_pagenode__podcastUnion = node__health_america_page | node__podcast

type taxonomy_term__the_health_of_america implements Node @dontInfer {
  drupal_id: String
  drupal_internal__tid: Int
  drupal_internal__revision_id: Int
  langcode: String
  status: Boolean
  name: String
  weight: Int
  changed: Date @dateformat
  default_langcode: Boolean
  revision_translation_affected: Boolean
  rh_action: String
  rh_redirect_response: Int
  relationships: taxonomy_term__the_health_of_americaRelationships
  vid: taxonomy_term__the_health_of_americaVid
}

type taxonomy_term__the_health_of_americaRelationships {
  node__health_america_page: [node__health_america_page] @link(by: "id", from: "node__health_america_page___NODE")
  node__page: [node__page] @link(by: "id", from: "node__page___NODE")
  node__podcast: [node__podcast] @link(by: "id", from: "node__podcast___NODE")
  node__video: [node__video] @link(by: "id", from: "node__video___NODE")
}

type node__page implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  revision_log: String
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  metatag_normalized: [node__pageMetatag_normalized]
  path: node__pagePath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__pageBody
  field_add_service_marks: String
  field_featured_image_visibility: Boolean
  field_meta_tags: node__pageField_meta_tags
  relationships: node__pageRelationships
  node_type: node__pageNode_type
  revision_uid: node__pageRevision_uid
  uid: node__pageUid
  field_featured_image: node__pageField_featured_image
  field_file_attachments: [node__pageField_file_attachments]
  field_hoa_content: node__pageField_hoa_content
}

type node__pageMetatag_normalized {
  tag: String
  attributes: node__pageMetatag_normalizedAttributes
}

type node__pageMetatag_normalizedAttributes {
  name: String
  content: String
  property: String
  rel: String
  href: String
}

type node__pagePath {
  alias: String
  pid: Int
  langcode: String
}

type node__pageBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__pageField_meta_tags {
  keywords: String
  title: String
  description: String
  abstract: String
  robots: String
  image_src: String
  referrer: String
  rights: String
  og_description: String
  og_image_secure_url: String
  og_image: String
  twitter_cards_type: String
  og_image_url: String
  twitter_cards_description: String
  twitter_cards_title: String
  twitter_cards_image: String
  og_title: String
  twitter_cards_image_alt: String
  twitter_cards_image_height: String
  twitter_cards_image_width: Date @dateformat
  og_image_alt: String
}

type node__pageRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_hoa_content: taxonomy_term__the_health_of_america @link(by: "id", from: "field_hoa_content___NODE")
}

type node__pageNode_type {
  drupal_internal__target_id: String
}

type node__pageRevision_uid {
  drupal_internal__target_id: Int
}

type node__pageUid {
  drupal_internal__target_id: Int
}

type node__pageField_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__pageField_file_attachments {
  display: Boolean
  description: String
  drupal_internal__target_id: Int
}

type node__pageField_hoa_content {
  drupal_internal__target_id: Int
}

type node__podcast implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__podcastPath
  rh_action: String
  rh_redirect_response: Int
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__podcastBody
  relationships: node__podcastRelationships
  node_type: node__podcastNode_type
  revision_uid: node__podcastRevision_uid
  uid: node__podcastUid
  field_featured_image: node__podcastField_featured_image
  field_hoa_content: node__podcastField_hoa_content
  field_podcast: [node__podcastField_podcast]
  field_states: [node__podcastField_states]
  field_topics: [node__podcastField_topics]
}

type node__podcastPath {
  alias: String
  pid: Int
  langcode: String
}

type node__podcastBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__podcastRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_hoa_content: taxonomy_term__the_health_of_america @link(by: "id", from: "field_hoa_content___NODE")
  field_states: [taxonomy_term__states] @link(by: "id", from: "field_states___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
  node__health_equity_plan_profile: [node__health_equity_plan_profile] @link(by: "id", from: "node__health_equity_plan_profile___NODE")
  node__health_america_page: [node__health_america_page] @link(by: "id", from: "node__health_america_page___NODE")
}

type node__podcastNode_type {
  drupal_internal__target_id: String
}

type node__podcastRevision_uid {
  drupal_internal__target_id: Int
}

type node__podcastUid {
  drupal_internal__target_id: Int
}

type node__podcastField_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__podcastField_hoa_content {
  drupal_internal__target_id: Int
}

type node__podcastField_podcast {
  display: Boolean
  description: String
  drupal_internal__target_id: Int
}

type node__podcastField_states {
  drupal_internal__target_id: Int
}

type node__podcastField_topics {
  drupal_internal__target_id: Int
}

type taxonomy_term__the_health_of_americaVid {
  drupal_internal__target_id: String
}

type node__hoa_insight implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__hoa_insightPath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__hoa_insightBody
  field_exclude_from_list: Boolean
  field_sub_title: String
  relationships: node__hoa_insightRelationships
  node_type: node__hoa_insightNode_type
  revision_uid: node__hoa_insightRevision_uid
  uid: node__hoa_insightUid
  field_download_infographic: [node__hoa_insightField_download_infographic]
  field_featured_image: node__hoa_insightField_featured_image
  field_topics: [node__hoa_insightField_topics]
  field_related_report: node__hoa_insightField_related_report
}

type node__hoa_insightPath {
  alias: String
  pid: Int
  langcode: String
}

type node__hoa_insightBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__hoa_insightRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
  field_related_report: node__health_america_page @link(by: "id", from: "field_related_report___NODE")
}

type node__hoa_insightNode_type {
  drupal_internal__target_id: String
}

type node__hoa_insightRevision_uid {
  drupal_internal__target_id: Int
}

type node__hoa_insightUid {
  drupal_internal__target_id: Int
}

type node__hoa_insightField_download_infographic {
  display: Boolean
  description: String
  drupal_internal__target_id: Int
}

type node__hoa_insightField_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__hoa_insightField_topics {
  drupal_internal__target_id: Int
}

type node__hoa_insightField_related_report {
  drupal_internal__target_id: Int
}

type node__health_america_pageNode_type {
  drupal_internal__target_id: String
}

type node__health_america_pageRevision_uid {
  drupal_internal__target_id: Int
}

type node__health_america_pageUid {
  drupal_internal__target_id: Int
}

type node__health_america_pageField_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__health_america_pageField_file_attachments {
  display: Boolean
  description: String
  drupal_internal__target_id: Int
}

type node__health_america_pageField_hoa_content {
  drupal_internal__target_id: Int
}

type node__health_america_pageField_related_pr {
  drupal_internal__target_id: Int
}

type node__health_america_pageField_topics {
  drupal_internal__target_id: Int
}

type node__health_america_pageField_appendix_data {
  display: Boolean
  description: String
  drupal_internal__target_id: Int
}

type node__health_america_pageField_download_infographic {
  display: Boolean
  description: String
  drupal_internal__target_id: Int
}

type node__health_america_pageField_curated_featured_content {
  drupal_internal__target_id: Int
}

type node__hoa_page implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__hoa_pagePath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  field_featured_image_visibility: Boolean
  relationships: node__hoa_pageRelationships
  node_type: node__hoa_pageNode_type
  revision_uid: node__hoa_pageRevision_uid
  uid: node__hoa_pageUid
  field_topics: [node__hoa_pageField_topics]
}

type node__hoa_pagePath {
  alias: String
  pid: Int
  langcode: String
}

type node__hoa_pageRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
}

type node__hoa_pageNode_type {
  drupal_internal__target_id: String
}

type node__hoa_pageRevision_uid {
  drupal_internal__target_id: Int
}

type node__hoa_pageUid {
  drupal_internal__target_id: Int
}

type node__hoa_pageField_topics {
  drupal_internal__target_id: Int
}

type node__hoa_topic implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__hoa_topicPath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  field_topic_news: [node__hoa_topicField_topic_news]
  relationships: node__hoa_topicRelationships
  node_type: node__hoa_topicNode_type
  revision_uid: node__hoa_topicRevision_uid
  uid: node__hoa_topicUid
  field_topic: node__hoa_topicField_topic
}

type node__hoa_topicPath {
  alias: String
  pid: Int
  langcode: String
}

type node__hoa_topicField_topic_news {
  uri: String
  title: String
}

type node__hoa_topicRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_topic: taxonomy_term__topic @link(by: "id", from: "field_topic___NODE")
}

type node__hoa_topicNode_type {
  drupal_internal__target_id: String
}

type node__hoa_topicRevision_uid {
  drupal_internal__target_id: Int
}

type node__hoa_topicUid {
  drupal_internal__target_id: Int
}

type node__hoa_topicField_topic {
  drupal_internal__target_id: Int
}

type node__health_equity_disparities implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__health_equity_disparitiesPath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__health_equity_disparitiesBody
  field_he_dis_content_source: node__health_equity_disparitiesField_he_dis_content_source
  field_he_statistic: String
  field_he_statistic_text: String
  relationships: node__health_equity_disparitiesRelationships
  node_type: node__health_equity_disparitiesNode_type
  revision_uid: node__health_equity_disparitiesRevision_uid
  uid: node__health_equity_disparitiesUid
  field_he_dis_featured_image: node__health_equity_disparitiesField_he_dis_featured_image
  field_topics: [node__health_equity_disparitiesField_topics]
}

type node__health_equity_disparitiesPath {
  langcode: String
}

type node__health_equity_disparitiesBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__health_equity_disparitiesField_he_dis_content_source {
  uri: String
  title: String
  url: String
}

type node__health_equity_disparitiesRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_he_dis_featured_image: file__file @link(by: "id", from: "field_he_dis_featured_image___NODE")
  field_topics: [taxonomy_term__topic] @link(by: "id", from: "field_topics___NODE")
}

type node__health_equity_disparitiesNode_type {
  drupal_internal__target_id: String
}

type node__health_equity_disparitiesRevision_uid {
  drupal_internal__target_id: Int
}

type node__health_equity_disparitiesUid {
  drupal_internal__target_id: Int
}

type node__health_equity_disparitiesField_he_dis_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__health_equity_disparitiesField_topics {
  drupal_internal__target_id: Int
}

type taxonomy_term__topicVid {
  drupal_internal__target_id: String
}

type node__videoNode_type {
  drupal_internal__target_id: String
}

type node__videoRevision_uid {
  drupal_internal__target_id: Int
}

type node__videoUid {
  drupal_internal__target_id: Int
}

type node__videoField_series {
  drupal_internal__target_id: Int
}

type node__videoField_tags {
  drupal_internal__target_id: Int
}

type node__videoField_hoa_content {
  drupal_internal__target_id: Int
}

type node__videoField_topics {
  drupal_internal__target_id: Int
}

type node__videoField_states {
  drupal_internal__target_id: Int
  arity: Int
}

type node__videoField_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type taxonomy_term__statesVid {
  drupal_internal__target_id: String
}

type node__health_equity_blogPath {
  alias: String
  pid: Int
  langcode: String
}

type node__health_equity_blogBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__health_equity_blogNode_type {
  drupal_internal__target_id: String
}

type node__health_equity_blogRevision_uid {
  drupal_internal__target_id: Int
}

type node__health_equity_blogUid {
  drupal_internal__target_id: Int
}

type node__health_equity_blogField_bcbs_plan {
  drupal_internal__target_id: Int
}

type node__health_equity_blogField_he_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__health_equity_blogField_he_hoa_related_content {
  drupal_internal__target_id: Int
}

type node__health_equity_blogField_he_related_content {
  drupal_internal__target_id: Int
}

type node__health_equity_blogField_states {
  drupal_internal__target_id: Int
}

type node__health_equity_blogField_topics {
  drupal_internal__target_id: Int
}

type node__health_equity_press_kit implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__health_equity_press_kitPath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__health_equity_press_kitBody
  field_he_title_category: String
  relationships: node__health_equity_press_kitRelationships
  node_type: node__health_equity_press_kitNode_type
  revision_uid: node__health_equity_press_kitRevision_uid
  uid: node__health_equity_press_kitUid
  field_he_pk_download: node__health_equity_press_kitField_he_pk_download
}

type node__health_equity_press_kitPath {
  langcode: String
}

type node__health_equity_press_kitBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__health_equity_press_kitRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
  field_he_pk_download: file__file @link(by: "id", from: "field_he_pk_download___NODE")
}

type node__health_equity_press_kitNode_type {
  drupal_internal__target_id: String
}

type node__health_equity_press_kitRevision_uid {
  drupal_internal__target_id: Int
}

type node__health_equity_press_kitUid {
  drupal_internal__target_id: Int
}

type node__health_equity_press_kitField_he_pk_download {
  display: Boolean
  description: String
  drupal_internal__target_id: Int
}

type file__fileUid {
  drupal_internal__target_id: Int
}

type node__health_equity_plan_profilePath {
  alias: String
  pid: Int
  langcode: String
}

type node__health_equity_plan_profileBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__health_equity_plan_profileNode_type {
  drupal_internal__target_id: String
}

type node__health_equity_plan_profileRevision_uid {
  drupal_internal__target_id: Int
}

type node__health_equity_plan_profileUid {
  drupal_internal__target_id: Int
}

type node__health_equity_plan_profileField_bcbs_plan {
  drupal_internal__target_id: Int
}

type node__health_equity_plan_profileField_he_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__health_equity_plan_profileField_he_hoa_related_content {
  drupal_internal__target_id: Int
}

type node__health_equity_plan_profileField_he_related_content {
  drupal_internal__target_id: Int
}

type node__health_equity_plan_profileField_states {
  drupal_internal__target_id: Int
  arity: Int
}

type node__health_equity_plan_profileField_topics {
  drupal_internal__target_id: Int
}

type taxonomy_term__bcbs_planVid {
  drupal_internal__target_id: String
}

type node__press_releaseNode_type {
  drupal_internal__target_id: String
}

type node__press_releaseRevision_uid {
  drupal_internal__target_id: Int
}

type node__press_releaseUid {
  drupal_internal__target_id: Int
}

type node__press_releaseField_bcbs_plan {
  drupal_internal__target_id: Int
}

type node__press_releaseField_file_attachments {
  display: Boolean
  description: String
  drupal_internal__target_id: Int
}

type node__press_releaseField_topics {
  drupal_internal__target_id: Int
}

type node__hoa_homepage implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__hoa_homepagePath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  content_translation_source: String
  content_translation_outdated: Boolean
  relationships: node__hoa_homepageRelationships
  node_type: node__hoa_homepageNode_type
  revision_uid: node__hoa_homepageRevision_uid
  uid: node__hoa_homepageUid
}

type node__hoa_homepagePath {
  alias: String
  pid: Int
  langcode: String
}

type node__hoa_homepageRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
}

type node__hoa_homepageNode_type {
  drupal_internal__target_id: String
}

type node__hoa_homepageRevision_uid {
  drupal_internal__target_id: Int
}

type node__hoa_homepageUid {
  drupal_internal__target_id: Int
}

type node__health_equity_faqs implements Node @dontInfer {
  drupal_id: String
  drupal_internal__nid: Int
  drupal_internal__vid: Int
  langcode: String
  revision_timestamp: Date @dateformat
  status: Boolean
  title: String
  created: Date @dateformat
  changed: Date @dateformat
  promote: Boolean
  sticky: Boolean
  default_langcode: Boolean
  revision_translation_affected: Boolean
  path: node__health_equity_faqsPath
  content_translation_source: String
  content_translation_outdated: Boolean
  body: node__health_equity_faqsBody
  relationships: node__health_equity_faqsRelationships
  node_type: node__health_equity_faqsNode_type
  revision_uid: node__health_equity_faqsRevision_uid
  uid: node__health_equity_faqsUid
}

type node__health_equity_faqsPath {
  langcode: String
}

type node__health_equity_faqsBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__health_equity_faqsRelationships {
  node_type: node_type__node_type @link(by: "id", from: "node_type___NODE")
  revision_uid: user__user @link(by: "id", from: "revision_uid___NODE")
  uid: user__user @link(by: "id", from: "uid___NODE")
}

type node__health_equity_faqsNode_type {
  drupal_internal__target_id: String
}

type node__health_equity_faqsRevision_uid {
  drupal_internal__target_id: Int
}

type node__health_equity_faqsUid {
  drupal_internal__target_id: Int
}

type node__bcbs_covid_articleNode_type {
  drupal_internal__target_id: String
}

type node__bcbs_covid_articleRevision_uid {
  drupal_internal__target_id: Int
}

type node__bcbs_covid_articleUid {
  drupal_internal__target_id: Int
}

type node__bcbs_covid_articleField_bcbs_plan {
  drupal_internal__target_id: Int
}

type node__bcbs_covid_articleField_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__bcbs_covid_articleField_states {
  drupal_internal__target_id: Int
  arity: Int
}

type node__health_equity_promotionPath {
  alias: String
  pid: Int
  langcode: String
}

type node__health_equity_promotionBody {
  value: String
  format: String
  processed: String
  summary: String
}

type node__health_equity_promotionNode_type {
  drupal_internal__target_id: String
}

type node__health_equity_promotionRevision_uid {
  drupal_internal__target_id: Int
}

type node__health_equity_promotionUid {
  drupal_internal__target_id: Int
}

type node__health_equity_promotionField_bcbs_plan {
  drupal_internal__target_id: Int
}

type node__health_equity_promotionField_he_featured_image {
  alt: String
  title: String
  width: Int
  height: Int
  drupal_internal__target_id: Int
}

type node__health_equity_promotionField_states {
  drupal_internal__target_id: Int
}

type node__health_equity_promotionField_topics {
  drupal_internal__target_id: Int
}

type taxonomy_term__sbh_length_filter implements Node @dontInfer {
  drupal_id: String
  drupal_internal__tid: Int
  drupal_internal__revision_id: Int
  langcode: String
  revision_created: Date @dateformat
  status: Boolean
  name: String
  weight: Int
  changed: Date @dateformat
  default_langcode: Boolean
  revision_translation_affected: Boolean
  metatag_normalized: [taxonomy_term__sbh_length_filterMetatag_normalized]
  path: taxonomy_term__sbh_length_filterPath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  vid: taxonomy_term__sbh_length_filterVid
}

type taxonomy_term__sbh_length_filterMetatag_normalized {
  tag: String
  attributes: taxonomy_term__sbh_length_filterMetatag_normalizedAttributes
}

type taxonomy_term__sbh_length_filterMetatag_normalizedAttributes {
  name: String
  content: String
}

type taxonomy_term__sbh_length_filterPath {
  langcode: String
}

type taxonomy_term__sbh_length_filterVid {
  drupal_internal__target_id: String
}

type taxonomy_term__sbh_content_filter implements Node @dontInfer {
  drupal_id: String
  drupal_internal__tid: Int
  drupal_internal__revision_id: Int
  langcode: String
  revision_created: Date @dateformat
  status: Boolean
  name: String
  weight: Int
  changed: Date @dateformat
  default_langcode: Boolean
  revision_translation_affected: Boolean
  metatag_normalized: [taxonomy_term__sbh_content_filterMetatag_normalized]
  path: taxonomy_term__sbh_content_filterPath
  rh_action: String
  rh_redirect_response: Int
  rh_redirect_fallback_action: String
  vid: taxonomy_term__sbh_content_filterVid
}

type taxonomy_term__sbh_content_filterMetatag_normalized {
  tag: String
  attributes: taxonomy_term__sbh_content_filterMetatag_normalizedAttributes
}

type taxonomy_term__sbh_content_filterMetatag_normalizedAttributes {
  name: String
  content: String
}

type taxonomy_term__sbh_content_filterPath {
  langcode: String
}

type taxonomy_term__sbh_content_filterVid {
  drupal_internal__target_id: String
}

type path_file_entity__path_file_entity implements Node @dontInfer {
  drupal_id: String
  drupal_internal__id: Int
  langcode: String
  name: String
  path: path_file_entity__path_file_entityPath
  status: Boolean
  created: Date @dateformat
  changed: Date @dateformat
  metatag_normalized: [path_file_entity__path_file_entityMetatag_normalized]
  fid: path_file_entity__path_file_entityFid
}

type path_file_entity__path_file_entityPath {
  alias: String
  pid: Int
  langcode: String
}

type path_file_entity__path_file_entityMetatag_normalized {
  tag: String
  attributes: path_file_entity__path_file_entityMetatag_normalizedAttributes
}

type path_file_entity__path_file_entityMetatag_normalizedAttributes {
  name: String
  content: String
}

type path_file_entity__path_file_entityFid {
  display: Boolean
  description: String
  drupal_internal__target_id: Int
}

type paragraph__paragraph_iframe implements Node @dontInfer {
  drupal_id: String
  drupal_internal__id: Int
  drupal_internal__revision_id: Int
  langcode: String
  status: Boolean
  created: Date @dateformat
  parent_id: String
  parent_type: String
  parent_field_name: String
  default_langcode: Boolean
  revision_translation_affected: Boolean
  content_translation_source: String
  content_translation_outdated: Boolean
}

type menu__menu implements Node @dontInfer {
  drupal_id: String
  label: String
}

type date_format__date_format implements Node @dontInfer {
  drupal_id: String
  label: String
}

type contact_form__contact_form implements Node @dontInfer {
  drupal_id: String
  langcode: String
  status: Boolean
  drupal_internal__id: String
  label: String
  recipients: [String]
  reply: String
  weight: Int
  message: String
  redirect: String
}

type block__block implements Node @dontInfer {
  drupal_id: String
  langcode: String
  status: Boolean
  dependencies: block__blockDependencies
  drupal_internal__id: String
  theme: String
  region: String
  weight: Int
  plugin: String
  settings: block__blockSettings
  visibility: block__blockVisibility
  third_party_settings: block__blockThird_party_settings
}

type block__blockDependencies {
  config: [String]
  module: [String]
  theme: [String]
  content: [String]
}

type block__blockSettings {
  id: String
  label: String
  label_display: String
  provider: String
  expand_all_items: Boolean
  use_site_logo: Boolean
  use_site_name: Boolean
  use_site_slogan: Boolean
  primary: Boolean
  secondary: Boolean
  status: Boolean
  info: String
  view_mode: String
  search_api_page: String
  follow: Boolean
  follow_parent: String
  label_link: Boolean
  label_type: String
  parent: String
  suggestion: String
  views_label: String
  menu_type: String
  style: String
  arrow: Int
  shadow: Int
  speed: String
  delay: String
  slide: String
  supposition: Int
  hoverintent: Int
  touch: String
  touchbh: String
  touchbp: String
  touchua: String
  touchual: String
  touchuam: String
  small: String
  smallbp: String
  smallua: String
  smallual: String
  smalluam: String
  smallact: String
  smallset: String
  smallasa: Int
  smallcmc: Int
  smallecm: String
  smallchc: Int
  smallech: String
  smallicm: String
  smallich: String
  smallamt: String
  smallabt: String
  supersubs: Int
  minwidth: String
  maxwidth: String
  multicolumn: Int
  multicolumn_depth: String
  multicolumn_levels: String
  pathlevels: String
  expanded: Int
  clone_parent: Int
  hide_linkdescription: Int
  add_linkdescription: Int
  link_depth_class: Int
  custom_list_class: String
  custom_item_class: String
  custom_link_class: String
  webform_id: String
  default_data: String
  redirect: Boolean
  items_per_page: String
}

type block__blockVisibility {
  request_path: block__blockVisibilityRequest_path
}

type block__blockVisibilityRequest_path {
  id: String
  negate: Boolean
  pages: String
}

type block__blockThird_party_settings {
  block_class: block__blockThird_party_settingsBlock_class
}

type block__blockThird_party_settingsBlock_class {
  classes: String
}

union node__health_america_pagenode__health_equity_plan_profilenode__podcastUnion = node__health_america_page | node__health_equity_plan_profile | node__podcast

union node__health_equity_blognode__health_equity_plan_profileUnion = node__health_equity_blog | node__health_equity_plan_profile

union node__health_america_pagenode__health_equity_blognode__health_equity_plan_profileUnion = node__health_america_page | node__health_equity_blog | node__health_equity_plan_profile

union node__health_equity_blognode__health_equity_plan_profilenode__health_equity_promotionUnion = node__health_equity_blog | node__health_equity_plan_profile | node__health_equity_promotion